azure:
  subscriptionID: 00d2caa5-cd29-46f7-845a-2f8ee0360ef5
  tenantID: 42f7676c-f455-423c-82f6-dc2d99791af7
  region: westeurope
  countUpdateDomains: 5
  countFaultDomains: 2

create:
  resourceGroup: true
  vnet: true
  availabilitySet: false
  natGateway: false

# identity:
  # name: identity-name
  # resourceGroup: identity-resource-group

# natGateway:
  # idleConnectionTimeoutMinutes: 4
  # zone: 1
  # migrateNatGatewayToIPAssociation: false # TODO(natipmigration) This can be removed in future versions when the ip migration has been completed.
  # ipAddresses:
  # - name: public-ip-0-name
  #   resourceGroup: public-ip-0-resource-group
  # - name: public-ip-1-name
  #   resourceGroup: public-ip-1-resource-group

resourceGroup:
  name: d071997-test-resource-group
  vnet:
    name: my-vnet
    # resourceGroup: vnet-resource-group
    cidr: 10.0.0.0/16
  subnet:
    serviceEndpoints: []

clusterName: test-namespace

networks:
  # worker: 10.250.0.0/19
  worker:
  zones:
    - name: "1"
      cidr: 10.0.10.0/24
      natGateway:
        zone: 1
    - name: "2"
      cidr: 10.0.11.0/24
      natGateway:

outputKeys:
  resourceGroupName: resourceGroupName
  vnetName: vnetName
  # vnetResourceGroup: vnet-resource-group
  availabilitySetID: availabilitySetID
  availabilitySetName: availabilitySetName
  countFaultDomains: countFaultDomains
  countUpdateDomains: countUpdateDomains
  routeTableName: routeTableName
  securityGroupName: securityGroupName
  # identityID: managedIdentityID
  # identityClientID: managedIdentityClientID
  subnetName: subnetName
  subnetNamePrefix: subnet_nodes_z
