// +build !ignore_autogenerated

/*
Copyright (c) 2021 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha2

import (
	unsafe "unsafe"

	azure "github.com/gardener/gardener-extension-provider-azure/pkg/apis/azure"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*AvailabilitySet)(nil), (*azure.AvailabilitySet)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_AvailabilitySet_To_azure_AvailabilitySet(a.(*AvailabilitySet), b.(*azure.AvailabilitySet), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*azure.AvailabilitySet)(nil), (*AvailabilitySet)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_azure_AvailabilitySet_To_v1alpha2_AvailabilitySet(a.(*azure.AvailabilitySet), b.(*AvailabilitySet), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*IdentityConfig)(nil), (*azure.IdentityConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_IdentityConfig_To_azure_IdentityConfig(a.(*IdentityConfig), b.(*azure.IdentityConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*azure.IdentityConfig)(nil), (*IdentityConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_azure_IdentityConfig_To_v1alpha2_IdentityConfig(a.(*azure.IdentityConfig), b.(*IdentityConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*IdentityStatus)(nil), (*azure.IdentityStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_IdentityStatus_To_azure_IdentityStatus(a.(*IdentityStatus), b.(*azure.IdentityStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*azure.IdentityStatus)(nil), (*IdentityStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_azure_IdentityStatus_To_v1alpha2_IdentityStatus(a.(*azure.IdentityStatus), b.(*IdentityStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*InfrastructureConfig)(nil), (*azure.InfrastructureConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_InfrastructureConfig_To_azure_InfrastructureConfig(a.(*InfrastructureConfig), b.(*azure.InfrastructureConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*azure.InfrastructureConfig)(nil), (*InfrastructureConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_azure_InfrastructureConfig_To_v1alpha2_InfrastructureConfig(a.(*azure.InfrastructureConfig), b.(*InfrastructureConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*InfrastructureStatus)(nil), (*azure.InfrastructureStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_InfrastructureStatus_To_azure_InfrastructureStatus(a.(*InfrastructureStatus), b.(*azure.InfrastructureStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*azure.InfrastructureStatus)(nil), (*InfrastructureStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_azure_InfrastructureStatus_To_v1alpha2_InfrastructureStatus(a.(*azure.InfrastructureStatus), b.(*InfrastructureStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NatGatewayConfig)(nil), (*azure.NatGatewayConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_NatGatewayConfig_To_azure_NatGatewayConfig(a.(*NatGatewayConfig), b.(*azure.NatGatewayConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*azure.NatGatewayConfig)(nil), (*NatGatewayConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_azure_NatGatewayConfig_To_v1alpha2_NatGatewayConfig(a.(*azure.NatGatewayConfig), b.(*NatGatewayConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NetworkConfig)(nil), (*azure.NetworkConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_NetworkConfig_To_azure_NetworkConfig(a.(*NetworkConfig), b.(*azure.NetworkConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*azure.NetworkConfig)(nil), (*NetworkConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_azure_NetworkConfig_To_v1alpha2_NetworkConfig(a.(*azure.NetworkConfig), b.(*NetworkConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NetworkStatus)(nil), (*azure.NetworkStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_NetworkStatus_To_azure_NetworkStatus(a.(*NetworkStatus), b.(*azure.NetworkStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*azure.NetworkStatus)(nil), (*NetworkStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_azure_NetworkStatus_To_v1alpha2_NetworkStatus(a.(*azure.NetworkStatus), b.(*NetworkStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PublicIPReference)(nil), (*azure.PublicIPReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_PublicIPReference_To_azure_PublicIPReference(a.(*PublicIPReference), b.(*azure.PublicIPReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*azure.PublicIPReference)(nil), (*PublicIPReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_azure_PublicIPReference_To_v1alpha2_PublicIPReference(a.(*azure.PublicIPReference), b.(*PublicIPReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RegionalTopology)(nil), (*azure.RegionalTopology)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_RegionalTopology_To_azure_RegionalTopology(a.(*RegionalTopology), b.(*azure.RegionalTopology), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*azure.RegionalTopology)(nil), (*RegionalTopology)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_azure_RegionalTopology_To_v1alpha2_RegionalTopology(a.(*azure.RegionalTopology), b.(*RegionalTopology), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ResourceGroup)(nil), (*azure.ResourceGroup)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ResourceGroup_To_azure_ResourceGroup(a.(*ResourceGroup), b.(*azure.ResourceGroup), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*azure.ResourceGroup)(nil), (*ResourceGroup)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_azure_ResourceGroup_To_v1alpha2_ResourceGroup(a.(*azure.ResourceGroup), b.(*ResourceGroup), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RouteTable)(nil), (*azure.RouteTable)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_RouteTable_To_azure_RouteTable(a.(*RouteTable), b.(*azure.RouteTable), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*azure.RouteTable)(nil), (*RouteTable)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_azure_RouteTable_To_v1alpha2_RouteTable(a.(*azure.RouteTable), b.(*RouteTable), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SecurityGroup)(nil), (*azure.SecurityGroup)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_SecurityGroup_To_azure_SecurityGroup(a.(*SecurityGroup), b.(*azure.SecurityGroup), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*azure.SecurityGroup)(nil), (*SecurityGroup)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_azure_SecurityGroup_To_v1alpha2_SecurityGroup(a.(*azure.SecurityGroup), b.(*SecurityGroup), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SingleSubnetZonalTopology)(nil), (*azure.SingleSubnetZonalTopology)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_SingleSubnetZonalTopology_To_azure_SingleSubnetZonalTopology(a.(*SingleSubnetZonalTopology), b.(*azure.SingleSubnetZonalTopology), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*azure.SingleSubnetZonalTopology)(nil), (*SingleSubnetZonalTopology)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_azure_SingleSubnetZonalTopology_To_v1alpha2_SingleSubnetZonalTopology(a.(*azure.SingleSubnetZonalTopology), b.(*SingleSubnetZonalTopology), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Subnet)(nil), (*azure.Subnet)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_Subnet_To_azure_Subnet(a.(*Subnet), b.(*azure.Subnet), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*azure.Subnet)(nil), (*Subnet)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_azure_Subnet_To_v1alpha2_Subnet(a.(*azure.Subnet), b.(*Subnet), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Topology)(nil), (*azure.Topology)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_Topology_To_azure_Topology(a.(*Topology), b.(*azure.Topology), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*azure.Topology)(nil), (*Topology)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_azure_Topology_To_v1alpha2_Topology(a.(*azure.Topology), b.(*Topology), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VNet)(nil), (*azure.VNet)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_VNet_To_azure_VNet(a.(*VNet), b.(*azure.VNet), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*azure.VNet)(nil), (*VNet)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_azure_VNet_To_v1alpha2_VNet(a.(*azure.VNet), b.(*VNet), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VNetStatus)(nil), (*azure.VNetStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_VNetStatus_To_azure_VNetStatus(a.(*VNetStatus), b.(*azure.VNetStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*azure.VNetStatus)(nil), (*VNetStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_azure_VNetStatus_To_v1alpha2_VNetStatus(a.(*azure.VNetStatus), b.(*VNetStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ZonalTopology)(nil), (*azure.ZonalTopology)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ZonalTopology_To_azure_ZonalTopology(a.(*ZonalTopology), b.(*azure.ZonalTopology), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*azure.ZonalTopology)(nil), (*ZonalTopology)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_azure_ZonalTopology_To_v1alpha2_ZonalTopology(a.(*azure.ZonalTopology), b.(*ZonalTopology), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Zone)(nil), (*azure.Zone)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_Zone_To_azure_Zone(a.(*Zone), b.(*azure.Zone), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*azure.Zone)(nil), (*Zone)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_azure_Zone_To_v1alpha2_Zone(a.(*azure.Zone), b.(*Zone), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha2_AvailabilitySet_To_azure_AvailabilitySet(in *AvailabilitySet, out *azure.AvailabilitySet, s conversion.Scope) error {
	out.Purpose = azure.Purpose(in.Purpose)
	out.ID = in.ID
	out.Name = in.Name
	out.CountFaultDomains = (*int32)(unsafe.Pointer(in.CountFaultDomains))
	out.CountUpdateDomains = (*int32)(unsafe.Pointer(in.CountUpdateDomains))
	return nil
}

// Convert_v1alpha2_AvailabilitySet_To_azure_AvailabilitySet is an autogenerated conversion function.
func Convert_v1alpha2_AvailabilitySet_To_azure_AvailabilitySet(in *AvailabilitySet, out *azure.AvailabilitySet, s conversion.Scope) error {
	return autoConvert_v1alpha2_AvailabilitySet_To_azure_AvailabilitySet(in, out, s)
}

func autoConvert_azure_AvailabilitySet_To_v1alpha2_AvailabilitySet(in *azure.AvailabilitySet, out *AvailabilitySet, s conversion.Scope) error {
	out.Purpose = Purpose(in.Purpose)
	out.ID = in.ID
	out.Name = in.Name
	out.CountFaultDomains = (*int32)(unsafe.Pointer(in.CountFaultDomains))
	out.CountUpdateDomains = (*int32)(unsafe.Pointer(in.CountUpdateDomains))
	return nil
}

// Convert_azure_AvailabilitySet_To_v1alpha2_AvailabilitySet is an autogenerated conversion function.
func Convert_azure_AvailabilitySet_To_v1alpha2_AvailabilitySet(in *azure.AvailabilitySet, out *AvailabilitySet, s conversion.Scope) error {
	return autoConvert_azure_AvailabilitySet_To_v1alpha2_AvailabilitySet(in, out, s)
}

func autoConvert_v1alpha2_IdentityConfig_To_azure_IdentityConfig(in *IdentityConfig, out *azure.IdentityConfig, s conversion.Scope) error {
	out.Name = in.Name
	out.ResourceGroup = in.ResourceGroup
	out.ACRAccess = (*bool)(unsafe.Pointer(in.ACRAccess))
	return nil
}

// Convert_v1alpha2_IdentityConfig_To_azure_IdentityConfig is an autogenerated conversion function.
func Convert_v1alpha2_IdentityConfig_To_azure_IdentityConfig(in *IdentityConfig, out *azure.IdentityConfig, s conversion.Scope) error {
	return autoConvert_v1alpha2_IdentityConfig_To_azure_IdentityConfig(in, out, s)
}

func autoConvert_azure_IdentityConfig_To_v1alpha2_IdentityConfig(in *azure.IdentityConfig, out *IdentityConfig, s conversion.Scope) error {
	out.Name = in.Name
	out.ResourceGroup = in.ResourceGroup
	out.ACRAccess = (*bool)(unsafe.Pointer(in.ACRAccess))
	return nil
}

// Convert_azure_IdentityConfig_To_v1alpha2_IdentityConfig is an autogenerated conversion function.
func Convert_azure_IdentityConfig_To_v1alpha2_IdentityConfig(in *azure.IdentityConfig, out *IdentityConfig, s conversion.Scope) error {
	return autoConvert_azure_IdentityConfig_To_v1alpha2_IdentityConfig(in, out, s)
}

func autoConvert_v1alpha2_IdentityStatus_To_azure_IdentityStatus(in *IdentityStatus, out *azure.IdentityStatus, s conversion.Scope) error {
	out.ID = in.ID
	out.ClientID = in.ClientID
	out.ACRAccess = in.ACRAccess
	return nil
}

// Convert_v1alpha2_IdentityStatus_To_azure_IdentityStatus is an autogenerated conversion function.
func Convert_v1alpha2_IdentityStatus_To_azure_IdentityStatus(in *IdentityStatus, out *azure.IdentityStatus, s conversion.Scope) error {
	return autoConvert_v1alpha2_IdentityStatus_To_azure_IdentityStatus(in, out, s)
}

func autoConvert_azure_IdentityStatus_To_v1alpha2_IdentityStatus(in *azure.IdentityStatus, out *IdentityStatus, s conversion.Scope) error {
	out.ID = in.ID
	out.ClientID = in.ClientID
	out.ACRAccess = in.ACRAccess
	return nil
}

// Convert_azure_IdentityStatus_To_v1alpha2_IdentityStatus is an autogenerated conversion function.
func Convert_azure_IdentityStatus_To_v1alpha2_IdentityStatus(in *azure.IdentityStatus, out *IdentityStatus, s conversion.Scope) error {
	return autoConvert_azure_IdentityStatus_To_v1alpha2_IdentityStatus(in, out, s)
}

func autoConvert_v1alpha2_InfrastructureConfig_To_azure_InfrastructureConfig(in *InfrastructureConfig, out *azure.InfrastructureConfig, s conversion.Scope) error {
	out.ResourceGroup = (*azure.ResourceGroup)(unsafe.Pointer(in.ResourceGroup))
	if err := Convert_v1alpha2_NetworkConfig_To_azure_NetworkConfig(&in.Networks, &out.Networks, s); err != nil {
		return err
	}
	out.Identity = (*azure.IdentityConfig)(unsafe.Pointer(in.Identity))
	return nil
}

// Convert_v1alpha2_InfrastructureConfig_To_azure_InfrastructureConfig is an autogenerated conversion function.
func Convert_v1alpha2_InfrastructureConfig_To_azure_InfrastructureConfig(in *InfrastructureConfig, out *azure.InfrastructureConfig, s conversion.Scope) error {
	return autoConvert_v1alpha2_InfrastructureConfig_To_azure_InfrastructureConfig(in, out, s)
}

func autoConvert_azure_InfrastructureConfig_To_v1alpha2_InfrastructureConfig(in *azure.InfrastructureConfig, out *InfrastructureConfig, s conversion.Scope) error {
	out.ResourceGroup = (*ResourceGroup)(unsafe.Pointer(in.ResourceGroup))
	if err := Convert_azure_NetworkConfig_To_v1alpha2_NetworkConfig(&in.Networks, &out.Networks, s); err != nil {
		return err
	}
	out.Identity = (*IdentityConfig)(unsafe.Pointer(in.Identity))
	return nil
}

// Convert_azure_InfrastructureConfig_To_v1alpha2_InfrastructureConfig is an autogenerated conversion function.
func Convert_azure_InfrastructureConfig_To_v1alpha2_InfrastructureConfig(in *azure.InfrastructureConfig, out *InfrastructureConfig, s conversion.Scope) error {
	return autoConvert_azure_InfrastructureConfig_To_v1alpha2_InfrastructureConfig(in, out, s)
}

func autoConvert_v1alpha2_InfrastructureStatus_To_azure_InfrastructureStatus(in *InfrastructureStatus, out *azure.InfrastructureStatus, s conversion.Scope) error {
	if err := Convert_v1alpha2_NetworkStatus_To_azure_NetworkStatus(&in.Networks, &out.Networks, s); err != nil {
		return err
	}
	if err := Convert_v1alpha2_ResourceGroup_To_azure_ResourceGroup(&in.ResourceGroup, &out.ResourceGroup, s); err != nil {
		return err
	}
	out.AvailabilitySets = *(*[]azure.AvailabilitySet)(unsafe.Pointer(&in.AvailabilitySets))
	out.RouteTables = *(*[]azure.RouteTable)(unsafe.Pointer(&in.RouteTables))
	out.SecurityGroups = *(*[]azure.SecurityGroup)(unsafe.Pointer(&in.SecurityGroups))
	out.Identity = (*azure.IdentityStatus)(unsafe.Pointer(in.Identity))
	out.Zoned = in.Zoned
	out.NatGatewayPublicIPMigrated = in.NatGatewayPublicIPMigrated
	return nil
}

// Convert_v1alpha2_InfrastructureStatus_To_azure_InfrastructureStatus is an autogenerated conversion function.
func Convert_v1alpha2_InfrastructureStatus_To_azure_InfrastructureStatus(in *InfrastructureStatus, out *azure.InfrastructureStatus, s conversion.Scope) error {
	return autoConvert_v1alpha2_InfrastructureStatus_To_azure_InfrastructureStatus(in, out, s)
}

func autoConvert_azure_InfrastructureStatus_To_v1alpha2_InfrastructureStatus(in *azure.InfrastructureStatus, out *InfrastructureStatus, s conversion.Scope) error {
	if err := Convert_azure_NetworkStatus_To_v1alpha2_NetworkStatus(&in.Networks, &out.Networks, s); err != nil {
		return err
	}
	if err := Convert_azure_ResourceGroup_To_v1alpha2_ResourceGroup(&in.ResourceGroup, &out.ResourceGroup, s); err != nil {
		return err
	}
	out.AvailabilitySets = *(*[]AvailabilitySet)(unsafe.Pointer(&in.AvailabilitySets))
	out.RouteTables = *(*[]RouteTable)(unsafe.Pointer(&in.RouteTables))
	out.SecurityGroups = *(*[]SecurityGroup)(unsafe.Pointer(&in.SecurityGroups))
	out.Identity = (*IdentityStatus)(unsafe.Pointer(in.Identity))
	out.Zoned = in.Zoned
	out.NatGatewayPublicIPMigrated = in.NatGatewayPublicIPMigrated
	return nil
}

// Convert_azure_InfrastructureStatus_To_v1alpha2_InfrastructureStatus is an autogenerated conversion function.
func Convert_azure_InfrastructureStatus_To_v1alpha2_InfrastructureStatus(in *azure.InfrastructureStatus, out *InfrastructureStatus, s conversion.Scope) error {
	return autoConvert_azure_InfrastructureStatus_To_v1alpha2_InfrastructureStatus(in, out, s)
}

func autoConvert_v1alpha2_NatGatewayConfig_To_azure_NatGatewayConfig(in *NatGatewayConfig, out *azure.NatGatewayConfig, s conversion.Scope) error {
	out.Enabled = in.Enabled
	out.IdleConnectionTimeoutMinutes = (*int32)(unsafe.Pointer(in.IdleConnectionTimeoutMinutes))
	out.IPAddresses = *(*[]azure.PublicIPReference)(unsafe.Pointer(&in.IPAddresses))
	out.Zone = (*int32)(unsafe.Pointer(in.Zone))
	return nil
}

// Convert_v1alpha2_NatGatewayConfig_To_azure_NatGatewayConfig is an autogenerated conversion function.
func Convert_v1alpha2_NatGatewayConfig_To_azure_NatGatewayConfig(in *NatGatewayConfig, out *azure.NatGatewayConfig, s conversion.Scope) error {
	return autoConvert_v1alpha2_NatGatewayConfig_To_azure_NatGatewayConfig(in, out, s)
}

func autoConvert_azure_NatGatewayConfig_To_v1alpha2_NatGatewayConfig(in *azure.NatGatewayConfig, out *NatGatewayConfig, s conversion.Scope) error {
	out.Enabled = in.Enabled
	out.IdleConnectionTimeoutMinutes = (*int32)(unsafe.Pointer(in.IdleConnectionTimeoutMinutes))
	out.Zone = (*int32)(unsafe.Pointer(in.Zone))
	out.IPAddresses = *(*[]PublicIPReference)(unsafe.Pointer(&in.IPAddresses))
	return nil
}

// Convert_azure_NatGatewayConfig_To_v1alpha2_NatGatewayConfig is an autogenerated conversion function.
func Convert_azure_NatGatewayConfig_To_v1alpha2_NatGatewayConfig(in *azure.NatGatewayConfig, out *NatGatewayConfig, s conversion.Scope) error {
	return autoConvert_azure_NatGatewayConfig_To_v1alpha2_NatGatewayConfig(in, out, s)
}

func autoConvert_v1alpha2_NetworkConfig_To_azure_NetworkConfig(in *NetworkConfig, out *azure.NetworkConfig, s conversion.Scope) error {
	if err := Convert_v1alpha2_VNet_To_azure_VNet(&in.VNet, &out.VNet, s); err != nil {
		return err
	}
	if err := Convert_v1alpha2_Topology_To_azure_Topology(&in.Topology, &out.Topology, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_NetworkConfig_To_azure_NetworkConfig is an autogenerated conversion function.
func Convert_v1alpha2_NetworkConfig_To_azure_NetworkConfig(in *NetworkConfig, out *azure.NetworkConfig, s conversion.Scope) error {
	return autoConvert_v1alpha2_NetworkConfig_To_azure_NetworkConfig(in, out, s)
}

func autoConvert_azure_NetworkConfig_To_v1alpha2_NetworkConfig(in *azure.NetworkConfig, out *NetworkConfig, s conversion.Scope) error {
	if err := Convert_azure_VNet_To_v1alpha2_VNet(&in.VNet, &out.VNet, s); err != nil {
		return err
	}
	if err := Convert_azure_Topology_To_v1alpha2_Topology(&in.Topology, &out.Topology, s); err != nil {
		return err
	}
	return nil
}

// Convert_azure_NetworkConfig_To_v1alpha2_NetworkConfig is an autogenerated conversion function.
func Convert_azure_NetworkConfig_To_v1alpha2_NetworkConfig(in *azure.NetworkConfig, out *NetworkConfig, s conversion.Scope) error {
	return autoConvert_azure_NetworkConfig_To_v1alpha2_NetworkConfig(in, out, s)
}

func autoConvert_v1alpha2_NetworkStatus_To_azure_NetworkStatus(in *NetworkStatus, out *azure.NetworkStatus, s conversion.Scope) error {
	if err := Convert_v1alpha2_VNetStatus_To_azure_VNetStatus(&in.VNet, &out.VNet, s); err != nil {
		return err
	}
	out.Subnets = *(*[]azure.Subnet)(unsafe.Pointer(&in.Subnets))
	return nil
}

// Convert_v1alpha2_NetworkStatus_To_azure_NetworkStatus is an autogenerated conversion function.
func Convert_v1alpha2_NetworkStatus_To_azure_NetworkStatus(in *NetworkStatus, out *azure.NetworkStatus, s conversion.Scope) error {
	return autoConvert_v1alpha2_NetworkStatus_To_azure_NetworkStatus(in, out, s)
}

func autoConvert_azure_NetworkStatus_To_v1alpha2_NetworkStatus(in *azure.NetworkStatus, out *NetworkStatus, s conversion.Scope) error {
	if err := Convert_azure_VNetStatus_To_v1alpha2_VNetStatus(&in.VNet, &out.VNet, s); err != nil {
		return err
	}
	out.Subnets = *(*[]Subnet)(unsafe.Pointer(&in.Subnets))
	return nil
}

// Convert_azure_NetworkStatus_To_v1alpha2_NetworkStatus is an autogenerated conversion function.
func Convert_azure_NetworkStatus_To_v1alpha2_NetworkStatus(in *azure.NetworkStatus, out *NetworkStatus, s conversion.Scope) error {
	return autoConvert_azure_NetworkStatus_To_v1alpha2_NetworkStatus(in, out, s)
}

func autoConvert_v1alpha2_PublicIPReference_To_azure_PublicIPReference(in *PublicIPReference, out *azure.PublicIPReference, s conversion.Scope) error {
	out.Name = in.Name
	out.ResourceGroup = in.ResourceGroup
	out.Zone = in.Zone
	return nil
}

// Convert_v1alpha2_PublicIPReference_To_azure_PublicIPReference is an autogenerated conversion function.
func Convert_v1alpha2_PublicIPReference_To_azure_PublicIPReference(in *PublicIPReference, out *azure.PublicIPReference, s conversion.Scope) error {
	return autoConvert_v1alpha2_PublicIPReference_To_azure_PublicIPReference(in, out, s)
}

func autoConvert_azure_PublicIPReference_To_v1alpha2_PublicIPReference(in *azure.PublicIPReference, out *PublicIPReference, s conversion.Scope) error {
	out.Name = in.Name
	out.ResourceGroup = in.ResourceGroup
	out.Zone = in.Zone
	return nil
}

// Convert_azure_PublicIPReference_To_v1alpha2_PublicIPReference is an autogenerated conversion function.
func Convert_azure_PublicIPReference_To_v1alpha2_PublicIPReference(in *azure.PublicIPReference, out *PublicIPReference, s conversion.Scope) error {
	return autoConvert_azure_PublicIPReference_To_v1alpha2_PublicIPReference(in, out, s)
}

func autoConvert_v1alpha2_RegionalTopology_To_azure_RegionalTopology(in *RegionalTopology, out *azure.RegionalTopology, s conversion.Scope) error {
	out.CIDR = in.CIDR
	out.ServiceEndpoints = *(*[]string)(unsafe.Pointer(&in.ServiceEndpoints))
	return nil
}

// Convert_v1alpha2_RegionalTopology_To_azure_RegionalTopology is an autogenerated conversion function.
func Convert_v1alpha2_RegionalTopology_To_azure_RegionalTopology(in *RegionalTopology, out *azure.RegionalTopology, s conversion.Scope) error {
	return autoConvert_v1alpha2_RegionalTopology_To_azure_RegionalTopology(in, out, s)
}

func autoConvert_azure_RegionalTopology_To_v1alpha2_RegionalTopology(in *azure.RegionalTopology, out *RegionalTopology, s conversion.Scope) error {
	out.CIDR = in.CIDR
	out.ServiceEndpoints = *(*[]string)(unsafe.Pointer(&in.ServiceEndpoints))
	return nil
}

// Convert_azure_RegionalTopology_To_v1alpha2_RegionalTopology is an autogenerated conversion function.
func Convert_azure_RegionalTopology_To_v1alpha2_RegionalTopology(in *azure.RegionalTopology, out *RegionalTopology, s conversion.Scope) error {
	return autoConvert_azure_RegionalTopology_To_v1alpha2_RegionalTopology(in, out, s)
}

func autoConvert_v1alpha2_ResourceGroup_To_azure_ResourceGroup(in *ResourceGroup, out *azure.ResourceGroup, s conversion.Scope) error {
	out.Name = in.Name
	return nil
}

// Convert_v1alpha2_ResourceGroup_To_azure_ResourceGroup is an autogenerated conversion function.
func Convert_v1alpha2_ResourceGroup_To_azure_ResourceGroup(in *ResourceGroup, out *azure.ResourceGroup, s conversion.Scope) error {
	return autoConvert_v1alpha2_ResourceGroup_To_azure_ResourceGroup(in, out, s)
}

func autoConvert_azure_ResourceGroup_To_v1alpha2_ResourceGroup(in *azure.ResourceGroup, out *ResourceGroup, s conversion.Scope) error {
	out.Name = in.Name
	return nil
}

// Convert_azure_ResourceGroup_To_v1alpha2_ResourceGroup is an autogenerated conversion function.
func Convert_azure_ResourceGroup_To_v1alpha2_ResourceGroup(in *azure.ResourceGroup, out *ResourceGroup, s conversion.Scope) error {
	return autoConvert_azure_ResourceGroup_To_v1alpha2_ResourceGroup(in, out, s)
}

func autoConvert_v1alpha2_RouteTable_To_azure_RouteTable(in *RouteTable, out *azure.RouteTable, s conversion.Scope) error {
	out.Purpose = azure.Purpose(in.Purpose)
	out.Name = in.Name
	return nil
}

// Convert_v1alpha2_RouteTable_To_azure_RouteTable is an autogenerated conversion function.
func Convert_v1alpha2_RouteTable_To_azure_RouteTable(in *RouteTable, out *azure.RouteTable, s conversion.Scope) error {
	return autoConvert_v1alpha2_RouteTable_To_azure_RouteTable(in, out, s)
}

func autoConvert_azure_RouteTable_To_v1alpha2_RouteTable(in *azure.RouteTable, out *RouteTable, s conversion.Scope) error {
	out.Purpose = Purpose(in.Purpose)
	out.Name = in.Name
	return nil
}

// Convert_azure_RouteTable_To_v1alpha2_RouteTable is an autogenerated conversion function.
func Convert_azure_RouteTable_To_v1alpha2_RouteTable(in *azure.RouteTable, out *RouteTable, s conversion.Scope) error {
	return autoConvert_azure_RouteTable_To_v1alpha2_RouteTable(in, out, s)
}

func autoConvert_v1alpha2_SecurityGroup_To_azure_SecurityGroup(in *SecurityGroup, out *azure.SecurityGroup, s conversion.Scope) error {
	out.Purpose = azure.Purpose(in.Purpose)
	out.Name = in.Name
	return nil
}

// Convert_v1alpha2_SecurityGroup_To_azure_SecurityGroup is an autogenerated conversion function.
func Convert_v1alpha2_SecurityGroup_To_azure_SecurityGroup(in *SecurityGroup, out *azure.SecurityGroup, s conversion.Scope) error {
	return autoConvert_v1alpha2_SecurityGroup_To_azure_SecurityGroup(in, out, s)
}

func autoConvert_azure_SecurityGroup_To_v1alpha2_SecurityGroup(in *azure.SecurityGroup, out *SecurityGroup, s conversion.Scope) error {
	out.Purpose = Purpose(in.Purpose)
	out.Name = in.Name
	return nil
}

// Convert_azure_SecurityGroup_To_v1alpha2_SecurityGroup is an autogenerated conversion function.
func Convert_azure_SecurityGroup_To_v1alpha2_SecurityGroup(in *azure.SecurityGroup, out *SecurityGroup, s conversion.Scope) error {
	return autoConvert_azure_SecurityGroup_To_v1alpha2_SecurityGroup(in, out, s)
}

func autoConvert_v1alpha2_SingleSubnetZonalTopology_To_azure_SingleSubnetZonalTopology(in *SingleSubnetZonalTopology, out *azure.SingleSubnetZonalTopology, s conversion.Scope) error {
	out.CIDR = in.CIDR
	out.ServiceEndpoints = *(*[]string)(unsafe.Pointer(&in.ServiceEndpoints))
	if in.NatGateway != nil {
		in, out := &in.NatGateway, &out.NatGateway
		*out = new(azure.NatGatewayConfig)
		if err := Convert_v1alpha2_NatGatewayConfig_To_azure_NatGatewayConfig(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.NatGateway = nil
	}
	return nil
}

// Convert_v1alpha2_SingleSubnetZonalTopology_To_azure_SingleSubnetZonalTopology is an autogenerated conversion function.
func Convert_v1alpha2_SingleSubnetZonalTopology_To_azure_SingleSubnetZonalTopology(in *SingleSubnetZonalTopology, out *azure.SingleSubnetZonalTopology, s conversion.Scope) error {
	return autoConvert_v1alpha2_SingleSubnetZonalTopology_To_azure_SingleSubnetZonalTopology(in, out, s)
}

func autoConvert_azure_SingleSubnetZonalTopology_To_v1alpha2_SingleSubnetZonalTopology(in *azure.SingleSubnetZonalTopology, out *SingleSubnetZonalTopology, s conversion.Scope) error {
	out.CIDR = in.CIDR
	out.ServiceEndpoints = *(*[]string)(unsafe.Pointer(&in.ServiceEndpoints))
	if in.NatGateway != nil {
		in, out := &in.NatGateway, &out.NatGateway
		*out = new(NatGatewayConfig)
		if err := Convert_azure_NatGatewayConfig_To_v1alpha2_NatGatewayConfig(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.NatGateway = nil
	}
	return nil
}

// Convert_azure_SingleSubnetZonalTopology_To_v1alpha2_SingleSubnetZonalTopology is an autogenerated conversion function.
func Convert_azure_SingleSubnetZonalTopology_To_v1alpha2_SingleSubnetZonalTopology(in *azure.SingleSubnetZonalTopology, out *SingleSubnetZonalTopology, s conversion.Scope) error {
	return autoConvert_azure_SingleSubnetZonalTopology_To_v1alpha2_SingleSubnetZonalTopology(in, out, s)
}

func autoConvert_v1alpha2_Subnet_To_azure_Subnet(in *Subnet, out *azure.Subnet, s conversion.Scope) error {
	out.Name = in.Name
	out.Purpose = azure.Purpose(in.Purpose)
	out.Zone = (*int32)(unsafe.Pointer(in.Zone))
	return nil
}

// Convert_v1alpha2_Subnet_To_azure_Subnet is an autogenerated conversion function.
func Convert_v1alpha2_Subnet_To_azure_Subnet(in *Subnet, out *azure.Subnet, s conversion.Scope) error {
	return autoConvert_v1alpha2_Subnet_To_azure_Subnet(in, out, s)
}

func autoConvert_azure_Subnet_To_v1alpha2_Subnet(in *azure.Subnet, out *Subnet, s conversion.Scope) error {
	out.Name = in.Name
	out.Purpose = Purpose(in.Purpose)
	out.Zone = (*int32)(unsafe.Pointer(in.Zone))
	return nil
}

// Convert_azure_Subnet_To_v1alpha2_Subnet is an autogenerated conversion function.
func Convert_azure_Subnet_To_v1alpha2_Subnet(in *azure.Subnet, out *Subnet, s conversion.Scope) error {
	return autoConvert_azure_Subnet_To_v1alpha2_Subnet(in, out, s)
}

func autoConvert_v1alpha2_Topology_To_azure_Topology(in *Topology, out *azure.Topology, s conversion.Scope) error {
	out.Regional = (*azure.RegionalTopology)(unsafe.Pointer(in.Regional))
	if in.SingleSubnetZonal != nil {
		in, out := &in.SingleSubnetZonal, &out.SingleSubnetZonal
		*out = new(azure.SingleSubnetZonalTopology)
		if err := Convert_v1alpha2_SingleSubnetZonalTopology_To_azure_SingleSubnetZonalTopology(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.SingleSubnetZonal = nil
	}
	if in.Zonal != nil {
		in, out := &in.Zonal, &out.Zonal
		*out = new(azure.ZonalTopology)
		if err := Convert_v1alpha2_ZonalTopology_To_azure_ZonalTopology(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.Zonal = nil
	}
	return nil
}

// Convert_v1alpha2_Topology_To_azure_Topology is an autogenerated conversion function.
func Convert_v1alpha2_Topology_To_azure_Topology(in *Topology, out *azure.Topology, s conversion.Scope) error {
	return autoConvert_v1alpha2_Topology_To_azure_Topology(in, out, s)
}

func autoConvert_azure_Topology_To_v1alpha2_Topology(in *azure.Topology, out *Topology, s conversion.Scope) error {
	out.Regional = (*RegionalTopology)(unsafe.Pointer(in.Regional))
	if in.SingleSubnetZonal != nil {
		in, out := &in.SingleSubnetZonal, &out.SingleSubnetZonal
		*out = new(SingleSubnetZonalTopology)
		if err := Convert_azure_SingleSubnetZonalTopology_To_v1alpha2_SingleSubnetZonalTopology(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.SingleSubnetZonal = nil
	}
	if in.Zonal != nil {
		in, out := &in.Zonal, &out.Zonal
		*out = new(ZonalTopology)
		if err := Convert_azure_ZonalTopology_To_v1alpha2_ZonalTopology(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.Zonal = nil
	}
	return nil
}

// Convert_azure_Topology_To_v1alpha2_Topology is an autogenerated conversion function.
func Convert_azure_Topology_To_v1alpha2_Topology(in *azure.Topology, out *Topology, s conversion.Scope) error {
	return autoConvert_azure_Topology_To_v1alpha2_Topology(in, out, s)
}

func autoConvert_v1alpha2_VNet_To_azure_VNet(in *VNet, out *azure.VNet, s conversion.Scope) error {
	out.Name = (*string)(unsafe.Pointer(in.Name))
	out.ResourceGroup = (*string)(unsafe.Pointer(in.ResourceGroup))
	out.CIDR = (*string)(unsafe.Pointer(in.CIDR))
	return nil
}

// Convert_v1alpha2_VNet_To_azure_VNet is an autogenerated conversion function.
func Convert_v1alpha2_VNet_To_azure_VNet(in *VNet, out *azure.VNet, s conversion.Scope) error {
	return autoConvert_v1alpha2_VNet_To_azure_VNet(in, out, s)
}

func autoConvert_azure_VNet_To_v1alpha2_VNet(in *azure.VNet, out *VNet, s conversion.Scope) error {
	out.Name = (*string)(unsafe.Pointer(in.Name))
	out.ResourceGroup = (*string)(unsafe.Pointer(in.ResourceGroup))
	out.CIDR = (*string)(unsafe.Pointer(in.CIDR))
	return nil
}

// Convert_azure_VNet_To_v1alpha2_VNet is an autogenerated conversion function.
func Convert_azure_VNet_To_v1alpha2_VNet(in *azure.VNet, out *VNet, s conversion.Scope) error {
	return autoConvert_azure_VNet_To_v1alpha2_VNet(in, out, s)
}

func autoConvert_v1alpha2_VNetStatus_To_azure_VNetStatus(in *VNetStatus, out *azure.VNetStatus, s conversion.Scope) error {
	out.Name = in.Name
	out.ResourceGroup = (*string)(unsafe.Pointer(in.ResourceGroup))
	return nil
}

// Convert_v1alpha2_VNetStatus_To_azure_VNetStatus is an autogenerated conversion function.
func Convert_v1alpha2_VNetStatus_To_azure_VNetStatus(in *VNetStatus, out *azure.VNetStatus, s conversion.Scope) error {
	return autoConvert_v1alpha2_VNetStatus_To_azure_VNetStatus(in, out, s)
}

func autoConvert_azure_VNetStatus_To_v1alpha2_VNetStatus(in *azure.VNetStatus, out *VNetStatus, s conversion.Scope) error {
	out.Name = in.Name
	out.ResourceGroup = (*string)(unsafe.Pointer(in.ResourceGroup))
	return nil
}

// Convert_azure_VNetStatus_To_v1alpha2_VNetStatus is an autogenerated conversion function.
func Convert_azure_VNetStatus_To_v1alpha2_VNetStatus(in *azure.VNetStatus, out *VNetStatus, s conversion.Scope) error {
	return autoConvert_azure_VNetStatus_To_v1alpha2_VNetStatus(in, out, s)
}

func autoConvert_v1alpha2_ZonalTopology_To_azure_ZonalTopology(in *ZonalTopology, out *azure.ZonalTopology, s conversion.Scope) error {
	if in.Zones != nil {
		in, out := &in.Zones, &out.Zones
		*out = make([]azure.Zone, len(*in))
		for i := range *in {
			if err := Convert_v1alpha2_Zone_To_azure_Zone(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Zones = nil
	}
	out.InternalCIDR = (*string)(unsafe.Pointer(in.InternalCIDR))
	return nil
}

// Convert_v1alpha2_ZonalTopology_To_azure_ZonalTopology is an autogenerated conversion function.
func Convert_v1alpha2_ZonalTopology_To_azure_ZonalTopology(in *ZonalTopology, out *azure.ZonalTopology, s conversion.Scope) error {
	return autoConvert_v1alpha2_ZonalTopology_To_azure_ZonalTopology(in, out, s)
}

func autoConvert_azure_ZonalTopology_To_v1alpha2_ZonalTopology(in *azure.ZonalTopology, out *ZonalTopology, s conversion.Scope) error {
	if in.Zones != nil {
		in, out := &in.Zones, &out.Zones
		*out = make([]Zone, len(*in))
		for i := range *in {
			if err := Convert_azure_Zone_To_v1alpha2_Zone(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Zones = nil
	}
	out.InternalCIDR = (*string)(unsafe.Pointer(in.InternalCIDR))
	return nil
}

// Convert_azure_ZonalTopology_To_v1alpha2_ZonalTopology is an autogenerated conversion function.
func Convert_azure_ZonalTopology_To_v1alpha2_ZonalTopology(in *azure.ZonalTopology, out *ZonalTopology, s conversion.Scope) error {
	return autoConvert_azure_ZonalTopology_To_v1alpha2_ZonalTopology(in, out, s)
}

func autoConvert_v1alpha2_Zone_To_azure_Zone(in *Zone, out *azure.Zone, s conversion.Scope) error {
	out.Name = in.Name
	out.CIDR = in.CIDR
	out.ServiceEndpoints = *(*[]string)(unsafe.Pointer(&in.ServiceEndpoints))
	if in.NatGateway != nil {
		in, out := &in.NatGateway, &out.NatGateway
		*out = new(azure.NatGatewayConfig)
		if err := Convert_v1alpha2_NatGatewayConfig_To_azure_NatGatewayConfig(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.NatGateway = nil
	}
	return nil
}

// Convert_v1alpha2_Zone_To_azure_Zone is an autogenerated conversion function.
func Convert_v1alpha2_Zone_To_azure_Zone(in *Zone, out *azure.Zone, s conversion.Scope) error {
	return autoConvert_v1alpha2_Zone_To_azure_Zone(in, out, s)
}

func autoConvert_azure_Zone_To_v1alpha2_Zone(in *azure.Zone, out *Zone, s conversion.Scope) error {
	out.Name = in.Name
	out.CIDR = in.CIDR
	out.ServiceEndpoints = *(*[]string)(unsafe.Pointer(&in.ServiceEndpoints))
	if in.NatGateway != nil {
		in, out := &in.NatGateway, &out.NatGateway
		*out = new(NatGatewayConfig)
		if err := Convert_azure_NatGatewayConfig_To_v1alpha2_NatGatewayConfig(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.NatGateway = nil
	}
	return nil
}

// Convert_azure_Zone_To_v1alpha2_Zone is an autogenerated conversion function.
func Convert_azure_Zone_To_v1alpha2_Zone(in *azure.Zone, out *Zone, s conversion.Scope) error {
	return autoConvert_azure_Zone_To_v1alpha2_Zone(in, out, s)
}
